version: '3.8'

services:
  web:
    build: .
    ports:
      - "1234:80"   # Maps host port 1234 to container port 80.
    volumes:
      - .:/app      # Mounts the current directory into the container for live updates.
      - /app/bin
      - /app/obj
    environment:
      # This connection string will be picked up by the .NET app.
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=postgres;Password=example
    depends_on:
      - db        # Ensures the DB service starts before the web app.

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

